import { NextResponse } from "next/server";
import { and, desc, eq, isNull } from "drizzle-orm";
import { db } from "@/lib/db";
import { inmAsignacionesPosicion, inmInmuebles, inmPosiciones, inmPropietarios, inmPublicaciones, inmTasaciones, inmTimeline, inmUsuarios } from "@/db/schema";
const clean=(v:unknown)=>typeof v==="string"?v.trim():"";
async function getSystemUser(tx:any){const email="sistema@inmobiliaria-alfaro.local";let [u]=await tx.select().from(inmUsuarios).where(eq(inmUsuarios.email,email)).limit(1);if(!u){const [c]=await tx.insert(inmUsuarios).values({nombre:"Usuario actual",email,rol:"usuario",activo:true}).$returningId();[u]=await tx.select().from(inmUsuarios).where(eq(inmUsuarios.id,c.id)).limit(1);}if(!u)throw new Error("No fue posible registrar el usuario de trazabilidad.");return u;}
const map=(r:any)=>({inmuebleId:r.inmuebleId,codigo:r.codigo,posicion:r.posicion?String(r.posicion).padStart(2,"0"):"—",nombre:r.referencia,ubicacion:[r.distrito,r.provincia,r.departamento,r.direccion].filter(Boolean).join(", ")||"Sin ubicación registrada",tipo:r.tipo,propietario:[r.propietarioNombres,r.propietarioApellidos].filter(Boolean).join(" ")||"Sin propietario",valorReferencia:r.valorReferencia,precioObjetivo:r.precioObjetivo,situacion:r.situacion});
async function approved(){return db.select({inmuebleId:inmInmuebles.id,codigo:inmInmuebles.codigo,tipo:inmInmuebles.tipo,referencia:inmInmuebles.referencia,direccion:inmInmuebles.direccion,distrito:inmInmuebles.distrito,provincia:inmInmuebles.provincia,departamento:inmInmuebles.departamento,propietarioNombres:inmPropietarios.nombres,propietarioApellidos:inmPropietarios.apellidos,posicion:inmPosiciones.numero,valorReferencia:inmTasaciones.valorReferencia,precioObjetivo:inmTasaciones.precioObjetivo,situacion:inmTasaciones.situacion}).from(inmTasaciones).innerJoin(inmInmuebles,eq(inmInmuebles.id,inmTasaciones.inmuebleId)).innerJoin(inmPropietarios,eq(inmPropietarios.id,inmInmuebles.propietarioId)).leftJoin(inmAsignacionesPosicion,and(eq(inmAsignacionesPosicion.inmuebleId,inmInmuebles.id),eq(inmAsignacionesPosicion.activa,true))).leftJoin(inmPosiciones,eq(inmPosiciones.id,inmAsignacionesPosicion.posicionId)).leftJoin(inmPublicaciones,eq(inmPublicaciones.inmuebleId,inmInmuebles.id)).where(and(eq(inmInmuebles.estado,"activo"),eq(inmTasaciones.situacion,"aprobado"),isNull(inmPublicaciones.id))).orderBy(desc(inmTasaciones.fechaActualizacion));}
export async function GET(){try{const rows=await approved();return NextResponse.json({ok:true,pendientes:rows.map(map)});}catch(error){console.error(error);return NextResponse.json({ok:false,error:"No se pudieron consultar los textos pendientes."},{status:500});}}
export async function POST(request:Request){try{const b=await request.json(),inmuebleId=Number(b.inmuebleId),texto=clean(b.texto),driveLink=clean(b.driveLink);if(!Number.isInteger(inmuebleId)||inmuebleId<=0)return NextResponse.json({ok:false,error:"Inmueble no válido."},{status:400});if(!texto)return NextResponse.json({ok:false,error:"El texto de publicación es obligatorio."},{status:400});if(!/^https?:\/\//i.test(driveLink))return NextResponse.json({ok:false,error:"El enlace de Google Drive debe ser una URL HTTP o HTTPS."},{status:400});const result=await db.transaction(async tx=>{const [p]=await tx.select().from(inmInmuebles).where(eq(inmInmuebles.id,inmuebleId)).limit(1);if(!p||p.estado!=="activo")throw new Error("El inmueble no está activo.");const [t]=await tx.select().from(inmTasaciones).where(and(eq(inmTasaciones.inmuebleId,inmuebleId),eq(inmTasaciones.situacion,"aprobado"))).limit(1);if(!t)throw new Error("El inmueble no tiene una tasación aprobada.");const [e]=await tx.select({id:inmPublicaciones.id}).from(inmPublicaciones).where(eq(inmPublicaciones.inmuebleId,inmuebleId)).limit(1);if(e)throw new Error("El inmueble ya tiene una publicación registrada.");const u=await getSystemUser(tx);await tx.insert(inmPublicaciones).values({inmuebleId,texto,driveLink,usuarioRegistroId:u.id,publicado:false});await tx.update(inmInmuebles).set({etapa:"listo_para_publicar"}).where(eq(inmInmuebles.id,inmuebleId));await tx.insert(inmTimeline).values({inmuebleId,evento:"publicacion_registrada",observacion:"Texto y enlace de Google Drive registrados. Inmueble listo para publicar.",usuarioId:u.id});return {etapa:"listo_para_publicar"};});return NextResponse.json({ok:true,...result},{status:201});}catch(error){const m=error instanceof Error?error.message:"No fue posible registrar la publicación.";return NextResponse.json({ok:false,error:m},{status:/no está activo|no tiene|ya tiene/i.test(m)?409:500});}}