"use client";
import {useEffect,useState} from "react";
import Link from "next/link";

type Item={id:string;posicion?:number;nombre:string;tipo:string;ubicacion:string;etapa?:string};
type Archivo={id:number;tipoDocumento:string;nombre:string;enlace:string;observacion?:string|null};
const tipos=[["DNI_PROPIETARIO","DNI del propietario"],["DOCUMENTO_PROPIEDAD","Documento de propiedad"],["COPIA_LITERAL","Copia literal"],["CONTRATO","Contrato"],["TASACION","Tasación"],["TEXTO_PUBLICACION","Texto de publicación"],["FOTO_INMUEBLE","Fotos"],["VIDEO_INMUEBLE","Video / recorrido"],["PLANO","Plano"],["RECIBO_SERVICIO","Recibo de servicio"],["OTRO","Otro"]];

export default function Page(){
 const [lista,setLista]=useState<Item[]>([]),[codigo,setCodigo]=useState(""),[d,setD]=useState<any>(null),[files,setFiles]=useState<Archivo[]>([]),[tab,setTab]=useState("Resumen"),[msg,setMsg]=useState(""),[err,setErr]=useState(""),[loading,setLoading]=useState(false),[form,setForm]=useState<any>({}),[doc,setDoc]=useState({tipoDocumento:"DNI_PROPIETARIO",nombre:"",enlace:"",observacion:""});
 const load=async(k:string)=>{if(!k)return;setLoading(true);try{const [a,b]=await Promise.all([fetch("/api/inmuebles/"+encodeURIComponent(k)),fetch("/api/inmuebles/"+encodeURIComponent(k)+"/archivos")]);const x=await a.json(),y=await b.json();if(!a.ok)throw new Error(x.error);if(!b.ok)throw new Error(y.error);setD(x);setFiles(y.archivos||[]);setForm(x.inmueble||{});}catch(e){setErr(e instanceof Error?e.message:"No se pudo cargar la ficha.");}finally{setLoading(false)}};
 useEffect(()=>{fetch("/api/cartera").then(r=>r.json()).then(x=>setLista(x.inmuebles||[]));const q=new URLSearchParams(location.search).get("codigo");if(q)setCodigo(q)},[]);
 useEffect(()=>{if(codigo)load(codigo)},[codigo]);
 const save=async()=>{setErr("");setMsg("");const r=await fetch("/api/inmuebles/"+encodeURIComponent(codigo),{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,propietario:{dni:d.inmueble.propietarioDni,nombres:d.inmueble.propietarioNombres,apellidos:d.inmueble.propietarioApellidos,telefono:d.inmueble.propietarioTelefono,email:d.inmueble.propietarioEmail,referenciaContacto:d.inmueble.propietarioReferencia}})});const x=await r.json();if(!r.ok)setErr(x.error);else{setMsg("Cambios guardados.");load(codigo)}};
 const addFile=async()=>{const r=await fetch("/api/inmuebles/"+encodeURIComponent(codigo)+"/archivos",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(doc)});const x=await r.json();if(!r.ok)setErr(x.error);else{setMsg("Documento registrado. El archivo permanece en Google Drive.");setDoc({tipoDocumento:"DNI_PROPIETARIO",nombre:"",enlace:"",observacion:""});load(codigo)}};
 const removeFile=async(id:number)=>{if(!confirm("¿Quitar este enlace? El archivo de Drive no se eliminará."))return;await fetch("/api/inmuebles/"+encodeURIComponent(codigo)+"/archivos?archivoId="+id,{method:"DELETE"});load(codigo)};
 const set=(k:string,v:string)=>setForm({...form,[k]:v});
 const field=(label:string,k:string)=><label className="text-xs font-semibold text-slate-500">{label}<input className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal text-slate-700 outline-none focus:border-emerald-400" value={form[k]??""} onChange={e=>set(k,e.target.value)}/></label>;
 const tabs=["Resumen","Propietario","Inmueble","Documentación","Tasación","Publicación"];
 return <main className="min-h-screen bg-[#f5f7fa] p-6 lg:p-8"><div className="mx-auto max-w-7xl">
 <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-600">Fase 2 · Ficha progresiva</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Datos del inmueble</h1><p className="mt-2 text-sm text-slate-500">Completa la información cuando esté disponible. La ficha no bloquea el flujo comercial.</p></div><Link href="/cartera" className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700">← Cartera</Link></header>
 <section className="mt-6 rounded-2xl bg-slate-900 p-5 text-white"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">Inmueble</p><select value={codigo} onChange={e=>setCodigo(e.target.value)} className="mt-2 w-full max-w-xl rounded-xl bg-white/10 px-3 py-3 text-sm outline-none"><option value="" className="text-slate-900">Seleccionar inmueble…</option>{lista.map(x=><option key={x.id} value={x.id} className="text-slate-900">{x.posicion?"Pos. "+String(x.posicion).padStart(2,"0")+" · ":""}{x.nombre} · {x.id}</option>)}</select></section>
 {loading&&<div className="mt-5 rounded-2xl bg-white p-5 text-sm text-slate-500">Cargando ficha…</div>}{err&&<div className="mt-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{err}</div>}{msg&&<div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{msg}</div>}
 {d&&!loading&&<><div className="mt-5 flex gap-2 overflow-x-auto rounded-2xl bg-white p-2 shadow-sm">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?"rounded-xl bg-slate-900 px-4 py-2.5 text-xs font-bold text-white":"rounded-xl px-4 py-2.5 text-xs font-bold text-slate-500"}>{t}</button>)}</div>
 <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-6">
 {tab==="Resumen"&&<><h2 className="text-2xl font-bold text-slate-950">{d.inmueble.referencia}</h2><p className="mt-1 text-sm text-slate-500">{d.inmueble.tipo} · {d.inmueble.codigo} · Posición {d.inmueble.posicion||"—"}</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Propietario",(d.inmueble.propietarioNombres||"")+" "+(d.inmueble.propietarioApellidos||"")],["Ubicación",d.inmueble.distrito||"Pendiente"],["Documentos",String(files.length)],["Tasación",d.tasacion?"Registrada":"Pendiente"]].map(x=><div key={x[0]} className="rounded-xl bg-[#f5f7fa] p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{x[0]}</p><p className="mt-1 text-sm font-semibold text-slate-800">{x[1]}</p></div>)}</div></>}
 {tab==="Propietario"&&<><div className="grid gap-4 sm:grid-cols-2">{[["DNI","propietarioDni"],["Nombres","propietarioNombres"],["Apellidos","propietarioApellidos"],["Teléfono","propietarioTelefono"],["Correo","propietarioEmail"],["Referencia de contacto","propietarioReferencia"]].map(x=><label key={x[1]} className="text-xs font-semibold text-slate-500">{x[0]}<input className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal text-slate-700" value={d.inmueble[x[1]]||""} onChange={e=>setD({...d,inmueble:{...d.inmueble,[x[1]]:e.target.value}})}/></label>)}</div><button onClick={save} className="mt-5 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Guardar propietario</button></>}
 {tab==="Inmueble"&&<><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["Referencia","referencia"],["Dirección","direccion"],["Distrito","distrito"],["Provincia","provincia"],["Departamento","departamento"],["Área terreno","areaTerreno"],["Área construida","areaConstruida"],["Habitaciones","habitaciones"],["Baños","banos"]].map(x=>field(x[0],x[1]))}</div><label className="mt-4 block text-xs font-semibold text-slate-500">Características<textarea className="mt-1 min-h-28 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal text-slate-700" value={form.caracteristicas||""} onChange={e=>set("caracteristicas",e.target.value)}/></label><label className="mt-4 block text-xs font-semibold text-slate-500">Observaciones<textarea className="mt-1 min-h-24 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal text-slate-700" value={form.observaciones||""} onChange={e=>set("observaciones",e.target.value)}/></label><button onClick={save} className="mt-5 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white">Guardar datos</button></>}
 {tab==="Documentación"&&<><div className="rounded-2xl bg-violet-50 p-4 text-sm text-slate-600"><b>Repositorio documental.</b> Los archivos permanecen en Drive; el sistema guarda el enlace y sus metadatos.</div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{tipos.map(x=><div key={x[0]} className="rounded-xl border border-slate-200 p-4"><span className="text-xs font-bold text-slate-700">{x[1]}</span><span className={files.some(f=>f.tipoDocumento===x[0])?"ml-2 rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-bold text-emerald-700":"ml-2 rounded-full bg-slate-100 px-2 py-1 text-[9px] font-bold text-slate-400"}>{files.some(f=>f.tipoDocumento===x[0])?"Registrado":"Pendiente"}</span></div>)}</div><div className="mt-6 rounded-2xl border border-slate-200 p-5"><h3 className="font-bold text-slate-900">Agregar archivo</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-500">Tipo<select className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" value={doc.tipoDocumento} onChange={e=>setDoc({...doc,tipoDocumento:e.target.value})}>{tipos.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label className="text-xs font-semibold text-slate-500">Nombre<input className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" value={doc.nombre} onChange={e=>setDoc({...doc,nombre:e.target.value})}/></label><label className="text-xs font-semibold text-slate-500 sm:col-span-2">Enlace Google Drive<input className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" placeholder="https://drive.google.com/..." value={doc.enlace} onChange={e=>setDoc({...doc,enlace:e.target.value})}/></label><label className="text-xs font-semibold text-slate-500 sm:col-span-2">Observación<input className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" value={doc.observacion} onChange={e=>setDoc({...doc,observacion:e.target.value})}/></label></div><button onClick={addFile} className="mt-4 rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white">Registrar enlace</button></div><div className="mt-5 space-y-2">{files.map(f=><div key={f.id} className="flex flex-col gap-3 rounded-xl border border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><b className="text-sm text-slate-800">{f.nombre}</b><p className="mt-1 text-[10px] font-bold uppercase text-slate-400">{tipos.find(x=>x[0]===f.tipoDocumento)?.[1]||f.tipoDocumento}</p></div><div className="flex gap-2"><a href={f.enlace} target="_blank" rel="noreferrer" className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white">Abrir Drive ↗</a><button onClick={()=>removeFile(f.id)} className="rounded-lg border px-3 py-2 text-xs font-semibold text-slate-500">Quitar</button></div></div>)}</div></>}
 {tab==="Tasación"&&<>{d.tasacion?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Fecha",d.tasacion.fechaTasacion],["Valor referencial",d.tasacion.valorReferencia?"S/ "+d.tasacion.valorReferencia:"—"],["Precio objetivo",d.tasacion.precioObjetivo?"S/ "+d.tasacion.precioObjetivo:"—"],["Situación",d.tasacion.situacion]].map(x=><div key={x[0]} className="rounded-xl bg-[#f5f7fa] p-4"><p className="text-[10px] font-bold uppercase text-slate-400">{x[0]}</p><p className="mt-1 text-sm font-bold">{x[1]}</p></div>)}</div>:<p className="text-sm text-slate-500">No hay tasación registrada todavía. <Link href="/registrar-tasaciones" className="font-semibold text-slate-900">Ir a tasaciones.</Link></p>}</>}
 {tab==="Publicación"&&<>{d.publicacion?<div className="space-y-4"><div className="whitespace-pre-wrap rounded-xl bg-[#f5f7fa] p-4 text-sm leading-6 text-slate-700">{d.publicacion.texto}</div>{d.publicacion.enlace&&<a href={d.publicacion.enlace} target="_blank" rel="noreferrer" className="inline-flex rounded-xl bg-slate-900 px-3 py-2 text-xs font-semibold text-white">Abrir referencia ↗</a>}</div>:<p className="text-sm text-slate-500">No hay publicación registrada todavía.</p>}</>}
 </section></>}
 </div></main>;
}